(function(){'use strict';Lampa.Lang.add({lampa_webhook:{ru:"Вебхуки",en:"Webhooks",be:"Вебхукі"}});const expression=/[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/i;const WebhookConfigs={types_player:{'inner':{"start":"start","close":"destroy"},'external':{"start":"external","close":"visibilitychange"}}};let isExternalPlayer=!1;function getCurrentPlayerEvents(){const usersPlayer=Lampa.Storage.field('player');const playerType=usersPlayer==='inner'?'inner':'external';return WebhookConfigs.types_player[playerType]}
function addSettingsItem(){Lampa.SettingsApi.addComponent({component:'webhooks',icon:'<svg xmlns="http://www.w3.org/2000/svg" width="54" height="54" viewBox="0 0 24 24" fill="none" stroke="#ffffff" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M4.876 13.61a4 4 0 1 0 6.124 3.39h6" /><path d="M15.066 20.502a4 4 0 1 0 1.934 -7.502c-.706 0 -1.424 .179 -2 .5l-3 -5.5" /><path d="M16 8a4 4 0 1 0 -8 0c0 1.506 .77 2.818 2 3.5l-3 5.5" /></svg>',name:Lampa.Lang.translate('lampa_webhook'),after:'player'})}
function initParamsComponent(){Lampa.SettingsApi.addParam({component:"webhooks",param:{name:'webhooks_enable',type:"trigger",value:!1,default:!1},field:{name:'Включить вебхуки',},onChange:function(value){if(value==="true"){let type_events=Lampa.Storage.field('webhooks_events');setupPlayerListeners(type_events);Lampa.Noty.show('Включено')}else if(value==="false"){clearPlayerListener();Lampa.Noty.show('🚫 Выключено')}
Lampa.Settings.update()}});Lampa.SettingsApi.addParam({component:'webhooks',param:{name:'webhooks_url',type:'input',placeholder:'http://...',values:'',default:''},field:{name:"URL адрес",},onChange:function(value){if(value.length>0){if(!expression.test(value)){Lampa.Noty.show('Указанное значение не является url адресом')}}},onRender:function(element){let isEnable=Lampa.Storage.field('webhooks_enable');element.toggle(!(!isEnable));element.toggleClass('hide',!isEnable)}});Lampa.SettingsApi.addParam({component:'webhooks',param:{name:'webhooks_method',type:'select',values:{'GET':'GET','POST':'POST'},default:'GET'},field:{name:'Метод'},onChange:function(value){Lampa.Settings.update()},onRender:function(element){let isEnable=Lampa.Storage.field('webhooks_enable');element.toggleClass('hide',!isEnable)}});Lampa.SettingsApi.addParam({component:'webhooks',param:{name:'webhooks_post_param_key_1',type:'input',placeholder:'Значение не задано',values:'',default:''},field:{name:"Ключ",},onRender:function(element){let isEnable=Lampa.Storage.field('webhooks_enable');const currentMethod=Lampa.Storage.field('webhooks_method');element.toggleClass('hide',(currentMethod!=='POST'||!isEnable))}});Lampa.SettingsApi.addParam({component:'webhooks',param:{name:'webhooks_post_param_value_1',type:'input',placeholder:'Значение не задано',values:'',default:''},field:{name:"Значение",},onRender:function(element){let isEnable=Lampa.Storage.field('webhooks_enable');const currentMethod=Lampa.Storage.field('webhooks_method');element.toggleClass('hide',(currentMethod!=='POST'||!isEnable))}});Lampa.SettingsApi.addParam({component:'webhooks',param:{name:'webhooks_events',type:'select',values:{'1':'Только вначале','2':'Только в конце','3':'Вначале и в конце'},default:'1'},field:{name:'Когда отправлять?'},onChange:function(value){if(Lampa.Storage.field('webhooks_enable')){setupPlayerListeners(value)}},onRender:function(element){let isEnable=Lampa.Storage.field('webhooks_enable');element.toggleClass('hide',!isEnable)}})}
function sendRequest(){let url=Lampa.Storage.field('webhooks_url');let method=Lampa.Storage.field('webhooks_method');let body=!1;if(!url)return;let net=new Lampa.Reguest();if(method==='POST'){let k=Lampa.Storage.field('webhooks_post_param_key_1');let v=Lampa.Storage.field('webhooks_post_param_value_1');if(k){body={[k]:v}}else{body={}}}
console.log('[Webhook] Sending:',method,url,body);net.silent(url,(data)=>{console.log('[Webhook] Success:',data)},(error)=>{console.log('[Webhook] Error:',error)},body,{native:!0,dataType:'text'})}
function externalListener(){if(document.visibilityState==='visible'&&isExternalPlayer){isExternalPlayer=!1;sendRequest()}}
function handleExternalStartOnly(){isExternalPlayer=!0}
function handleExternalStartAndSend(){isExternalPlayer=!0;sendRequest()}
function setupPlayerListeners(value){clearPlayerListener();if(!Lampa.Player||!Lampa.Player.listener){console.log('[Webhook] Player listener not ready yet');return}
const events=getCurrentPlayerEvents();const val=parseInt(value);try{switch(val){case 1:Lampa.Player.listener.follow(events.start,sendRequest);break;case 2:if(events.start==="external"){Lampa.Player.listener.follow(events.start,handleExternalStartOnly);document.addEventListener('visibilitychange',externalListener)}else{Lampa.Player.listener.follow(events.close,sendRequest)}
break;case 3:if(events.start==="external"){Lampa.Player.listener.follow(events.start,handleExternalStartAndSend);document.addEventListener('visibilitychange',externalListener)}else{Lampa.Player.listener.follow(events.start,sendRequest);Lampa.Player.listener.follow(events.close,sendRequest)}
break}}catch(e){console.error('[Webhook] Error setting listener:',e)}}
function clearPlayerListener(){if(!Lampa.Player||!Lampa.Player.listener)return;const events=getCurrentPlayerEvents();try{Lampa.Player.listener.remove(events.start,sendRequest);Lampa.Player.listener.remove(events.close,sendRequest);Lampa.Player.listener.remove(events.start,handleExternalStartOnly);Lampa.Player.listener.remove(events.start,handleExternalStartAndSend);document.removeEventListener('visibilitychange',externalListener);isExternalPlayer=!1}catch(e){console.warn('[Webhook] Warning clearing listener:',e)}}
function startPlugin(){addSettingsItem();initParamsComponent();if(Lampa.Storage.field('webhooks_enable')){let type_events=Lampa.Storage.field('webhooks_events');setupPlayerListeners(type_events)}}
if(window.appready){startPlugin()}else{Lampa.Listener.follow('app',function(e){if(e.type==='ready'){startPlugin()}})}})()